/**
 * Agent Avatars
 * 
 * Loads avatar URLs from personality JSON files generated by personality-creator.
 */

import { readFileSync, existsSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PERSONALITIES_DIR = resolve(__dirname, "../../personalities");

// =============================================================================
// AVATAR CACHE (loaded from personality files)
// =============================================================================

/**
 * Avatars loaded from personality JSON files
 */
const loadedAvatars = new Map<string, string>();
let avatarsLoaded = false;

/**
 * Load all avatars from personality files
 */
function loadAvatarsFromPersonalities(): void {
  if (avatarsLoaded) return;
  
  try {
    if (!existsSync(PERSONALITIES_DIR)) {
      avatarsLoaded = true;
      return;
    }
    
    const files = readdirSync(PERSONALITIES_DIR).filter(f => f.endsWith(".json"));
    
    for (const file of files) {
      try {
        const filepath = resolve(PERSONALITIES_DIR, file);
        const content = readFileSync(filepath, "utf-8");
        const data = JSON.parse(content);
        
        if (data.handle && data.avatar) {
          loadedAvatars.set(data.handle.toLowerCase(), data.avatar);
        }
      } catch {
        // Skip invalid files
      }
    }
  } catch {
    // Directory doesn't exist or can't be read
  }
  
  avatarsLoaded = true;
}

/**
 * Fallback avatar for agents without a custom one
 */
export const FALLBACK_AVATAR = "https://api.dicebear.com/7.x/bottts/svg?seed=default";

/**
 * Custom uploaded avatars (agent handle -> URL)
 * In production, these would be stored in a database
 */
const customAvatars = new Map<string, string>();

// =============================================================================
// FUNCTIONS
// =============================================================================

/**
 * Get avatar URL for an agent
 */
export function getAgentAvatar(handle: string): string {
  loadAvatarsFromPersonalities();
  
  const handleLower = handle.toLowerCase();
  
  // Check custom avatar first
  const custom = customAvatars.get(handleLower);
  if (custom) return custom;
  
  // Check avatars loaded from personality files
  const loaded = loadedAvatars.get(handleLower);
  if (loaded) return loaded;
  
  // Generate deterministic avatar based on handle
  return `https://api.dicebear.com/7.x/bottts/svg?seed=${encodeURIComponent(handle)}`;
}

/**
 * Set custom avatar for an agent
 */
export function setAgentAvatar(handle: string, url: string): void {
  customAvatars.set(handle.toLowerCase(), url);
}

/**
 * Remove custom avatar (revert to default)
 */
export function removeAgentAvatar(handle: string): void {
  customAvatars.delete(handle.toLowerCase());
}

/**
 * Get all avatar URLs (for API response)
 */
export function getAllAvatars(): Record<string, string> {
  loadAvatarsFromPersonalities();
  
  const all: Record<string, string> = {};
  
  // Start with loaded avatars from personality files
  for (const [handle, url] of loadedAvatars) {
    all[handle] = url;
  }
  
  // Overlay custom avatars
  for (const [handle, url] of customAvatars) {
    all[handle] = url;
  }
  
  return all;
}

/**
 * Default emoji avatars (fallback for chat display)
 */
const DEFAULT_EMOJIS: Record<string, string> = {
  naval: "🧘",
  elon: "🚀", 
  elonmusk: "🚀",
  karpathy: "🤖",
  degen: "🐸",
  pmarca: "💼",
  demishassabis: "🧠",
};

/**
 * Get emoji avatar for an agent
 */
export function getAgentEmoji(handle: string): string {
  return DEFAULT_EMOJIS[handle.toLowerCase()] || "👤";
}
