/**
 * Agent Factory
 * 
 * Creates and manages agent instances.
 * Loads personalities from JSON files generated by personality-creator.
 */

import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import type { Agent, AgentPersonality, AgentState } from "../types/index.js";
import { getAvailablePersonalities, getPersonality } from "./personalities.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PERSONALITIES_DIR = resolve(__dirname, "../../personalities");

// =============================================================================
// DISPLAY NAME CACHE
// =============================================================================

interface GeneratedAgentFile {
  displayName: string;
  avatar?: string;
}

const displayNameCache = new Map<string, string>();
const avatarCache = new Map<string, string>();

function loadDisplayInfo(handle: string): void {
  if (displayNameCache.has(handle)) return;
  
  const filepath = resolve(PERSONALITIES_DIR, `${handle}.json`);
  if (!existsSync(filepath)) {
    displayNameCache.set(handle, `@${handle}`);
    return;
  }
  
  try {
    const content = readFileSync(filepath, "utf-8");
    const data: GeneratedAgentFile = JSON.parse(content);
    displayNameCache.set(handle, data.displayName || `@${handle}`);
    if (data.avatar) avatarCache.set(handle, data.avatar);
  } catch {
    displayNameCache.set(handle, `@${handle}`);
  }
}

// =============================================================================
// AGENT FACTORY
// =============================================================================

export class AgentFactory {
  private agents: Map<string, Agent> = new Map();

  /**
   * Create an agent from a loaded personality
   */
  createPresetAgent(handle: string): Agent {
    const personality = getPersonality(handle);
    
    if (!personality) {
      throw new Error(`Personality not found: ${handle}`);
    }

    loadDisplayInfo(handle);
    
    const agent: Agent = {
      id: `agent_${handle}`,
      handle,
      displayName: displayNameCache.get(handle) || `@${handle}`,
      avatar: avatarCache.get(handle),
      personality: { ...personality },
      traderId: `trader_${handle}`,
      userId: `user_${handle}`,
    };

    this.agents.set(agent.id, agent);
    return agent;
  }

  /**
   * Create all available preset agents
   */
  createAllPresetAgents(): Agent[] {
    const handles = getAvailablePersonalities();
    return handles.map(handle => this.createPresetAgent(handle));
  }

  /**
   * Create a custom agent from a personality file path
   */
  createAgentFromFile(filepath: string): Agent {
    if (!existsSync(filepath)) {
      throw new Error(`Personality file not found: ${filepath}`);
    }

    const content = readFileSync(filepath, "utf-8");
    const data = JSON.parse(content);
    
    const personality: AgentPersonality = {
      riskProfile: data.personality.riskProfile,
      tradingStyle: data.personality.tradingStyle,
      maxPositionPercent: data.personality.maxPositionPercent,
      minConfidenceToTrade: data.personality.minConfidenceToTrade,
      tone: data.personality.tone,
      verbosity: data.personality.verbosity,
      usesEmoji: false,
      catchphrases: data.personality.catchphrases || [],
      expertise: data.personality.expertise || [],
      avoids: data.personality.avoids || [],
      bio: data.personality.bio,
      tradingPhilosophy: data.personality.tradingPhilosophy,
    };

    const agent: Agent = {
      id: data.id || `agent_${data.handle}`,
      handle: data.handle,
      displayName: data.displayName || `@${data.handle}`,
      avatar: data.avatar,
      personality,
      traderId: `trader_${data.handle}`,
      userId: `user_${data.handle}`,
    };

    this.agents.set(agent.id, agent);
    return agent;
  }

  /**
   * Get an agent by ID
   */
  getAgent(id: string): Agent | undefined {
    return this.agents.get(id);
  }

  /**
   * Get all agents
   */
  getAllAgents(): Agent[] {
    return Array.from(this.agents.values());
  }

  /**
   * Initialize agent state for a trading session
   */
  initializeAgentState(agent: Agent, balance: number = 10000): AgentState {
    return {
      agentId: agent.id,
      balance,
      availableBalance: balance,
      lockedBalance: 0,
      positions: new Map(),
      onFloor: true,
      activeSideChats: [],
      tentativeAgreements: [],
      researchContext: '',
    };
  }
}

// =============================================================================
// SINGLETON FACTORY
// =============================================================================

let factoryInstance: AgentFactory | null = null;

export function getAgentFactory(): AgentFactory {
  if (!factoryInstance) {
    factoryInstance = new AgentFactory();
  }
  return factoryInstance;
}

/**
 * Check if agent would be interested in a topic
 */
export function wouldAgentBeInterested(agent: Agent, tags: string[]): boolean {
  const { expertise, avoids } = agent.personality;
  
  const isAvoided = tags.some(tag => 
    avoids.some(avoid => tag.toLowerCase().includes(avoid.toLowerCase()))
  );
  
  return !isAvoided;
}
