/**
 * Agent Personalities Loader
 * 
 * Loads agent personalities from JSON files generated by personality-creator.
 */

import { readFileSync, readdirSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import type { AgentPersonality } from "../types/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PERSONALITIES_DIR = resolve(__dirname, "../../personalities");

// =============================================================================
// PERSONALITY LOADER
// =============================================================================

interface GeneratedAgent {
  id: string;
  handle: string;
  displayName: string;
  avatar?: string;
  twitterId?: string;
  generatedAt: string;
  personality: Omit<AgentPersonality, 'usesEmoji'>;
}

/**
 * Load a personality from a JSON file
 */
function loadPersonalityFromFile(filename: string): AgentPersonality | null {
  const filepath = resolve(PERSONALITIES_DIR, filename);
  
  if (!existsSync(filepath)) {
    console.warn(`[Personalities] File not found: ${filepath}`);
    return null;
  }

  try {
    const content = readFileSync(filepath, "utf-8");
    const data: GeneratedAgent = JSON.parse(content);
    
    const personality: AgentPersonality = {
      riskProfile: data.personality.riskProfile,
      tradingStyle: data.personality.tradingStyle,
      maxPositionPercent: data.personality.maxPositionPercent,
      minConfidenceToTrade: data.personality.minConfidenceToTrade,
      tone: data.personality.tone,
      verbosity: data.personality.verbosity,
      usesEmoji: false,
      catchphrases: data.personality.catchphrases || [],
      expertise: data.personality.expertise || [],
      avoids: data.personality.avoids || [],
      bio: data.personality.bio,
      tradingPhilosophy: data.personality.tradingPhilosophy,
    };

    return personality;
  } catch (err) {
    console.error(`[Personalities] Error loading ${filename}:`, err);
    return null;
  }
}

/**
 * Load all personalities from the personalities directory
 */
function loadAllPersonalities(): Map<string, AgentPersonality> {
  const personalities = new Map<string, AgentPersonality>();

  if (!existsSync(PERSONALITIES_DIR)) {
    console.warn(`[Personalities] Directory not found: ${PERSONALITIES_DIR}`);
    return personalities;
  }

  const files = readdirSync(PERSONALITIES_DIR).filter(f => f.endsWith(".json"));
  
  for (const file of files) {
    const handle = file.replace(".json", "");
    const personality = loadPersonalityFromFile(file);
    
    if (personality) {
      personalities.set(handle, personality);
      console.log(`[Personalities] Loaded: @${handle}`);
    }
  }

  return personalities;
}

// =============================================================================
// LOADED PERSONALITIES
// =============================================================================

const LOADED_PERSONALITIES = loadAllPersonalities();

// =============================================================================
// EXPORTS
// =============================================================================

export const PRESET_PERSONALITIES: Record<string, AgentPersonality> = {};

for (const [handle, personality] of LOADED_PERSONALITIES) {
  PRESET_PERSONALITIES[handle] = personality;
}

export type PresetPersonalityKey = string;

/**
 * Get all available personality keys
 */
export function getAvailablePersonalities(): string[] {
  return Array.from(LOADED_PERSONALITIES.keys());
}

/**
 * Get a personality by handle
 */
export function getPersonality(handle: string): AgentPersonality | undefined {
  return LOADED_PERSONALITIES.get(handle);
}
